version: '3'
services:
  varnish:
    build: .
    ports:
    - "80:80"
    environment:
      VARNISH_SIZE: 8g
    tmpfs:
      - /var/lib/varnish:exec
  tile:
    image: maptiler/tileserver-gl
    volumes:
    - .:/data
    command: -p 8080 --verbose -c /data/config.json
